create table attachment(
                           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           habit_progress_id INT REFERENCES habit_progress(id),
                           type int NOT NULL,
                           url varchar NOT NULL
);

CREATE TABLE "user" (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(50) NOT NULL,
                        avatar_url varchar,
                        keycloak_sub VARCHAR(255) UNIQUE NOT NULL
);

create table habit (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       progress_frequency int NOT NULL,
                       goal_type INT NOT NULL,
                       measurement INT NOT NULL,
                       goal INT not null,
                       updated_at timestamp not null,
                       created_at date not null,
                       author_id INT references "user"(id),
                       is_active bool NOT NULL
);


create table habit_progress(
                               id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id INT REFERENCES "user"(id),
                               habit_id INT REFERENCES habit(id),
                               progress INT NOT NULL,
                               sent_at timestamp NOT NULL
);

CREATE TABLE user_habit (
                            user_id INT REFERENCES "user"(id),
                            habit_id INT REFERENCES habit(id),
                            progress INT default 0,
                            is_deleted boolean DEFAULT true,
                            primary key (habit_id, user_id)
);

create table user_friend (
                             user_id INT REFERENCES "user"(id),
                             friend_id INT REFERENCES "user"(id),
                             PRIMARY KEY (user_id, friend_id)
);

create table code(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     user_id INT REFERENCES "user"(id),
                     code varchar
)
